### ISSUE TITLE
提问及功能建议！

### ISSUE THREAD

**Issue by nomoneynolife** [dwj0/Remote-management#1]
提问1；
设置中的原密是多少，密码对应的是user.db吗

建议1；
添加一个软件打开密码，防止被拷贝别人直接用！

**Comment by nomoneynolife** [comment]
因为解压后，再设置中填入新密码会提示原密码错误！

再readme中看到有添加启动密码的功能，设置中未看见！

**Comment by dwj0** [comment]
原始密码为空，你把原密码中的*删除就行
