### ISSUE TITLE
希望在删除主机的时候，可以有个确认提示

### ISSUE THREAD

**Issue by sifanx** [dwj0/Remote-management#10]
有时候不小心点了删除主机，结果就直接删除了，想恢复都没机会，有个是否删除的确认提示，会更人性化一点。

**Comment by dwj0** [comment]
有恢复机会的， 软件刚启动时， 会在安装目录下生成一个user.db.bak文件，你可以用这个文件还原。但如果你关掉了软件后， 又启动了软件，这真的没办法了
