### ISSUE TITLE
系统区域设置勾选了UTF8会导致程序乱码

### ISSUE THREAD

**Issue by ijglb** [dwj0/Remote-management#12]
![QQ截图20220920224427](https://user-images.githubusercontent.com/31527814/191290616-c7ba860b-7509-4223-bfb0-e65a952464c1.png)

![QQ截图20220920224338](https://user-images.githubusercontent.com/31527814/191290630-f3a87d03-9333-40d9-8a8a-9c0c6e5e550c.png)

**Comment by dwj0** [comment]
我知道的，我没有用unicode编码写，你可以把源码改一下。然后共享下。
或者等到我哪天有这个需求了，我再改。
