### ISSUE TITLE
能否增加telnet协议和telnet ftp连接

### ISSUE THREAD

**Issue by yuyu127748** [dwj0/Remote-management#3]
工作中还会用到telent协议，请问大佬能否增加telnet协议和telnet ftp连接 ，谢谢

**Comment by dwj0** [comment]
暂时不考虑。因为telnet没找到命令行，如果你实现了可以pull   requests

**Comment by yuyu127748** [comment]
好吧，谢谢了。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月12日(周六) 晚上8:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dwj0/Remote-management] 能否增加telnet协议和telnet ftp连接 (#3)




 
暂时不考虑。因为telnet没找到命令行，如果你实现了可以pull   requests
